// <auto-generated />
using System;
using IASI_IntelligentIndustrialSolutions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace IASI_IntelligentIndustrialSolutions.Migrations
{
    [DbContext(typeof(IasiContext))]
    [Migration("20240513190339_intitdb")]
    partial class intitdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IASI_IntelligentIndustrialSolutions.Models.Consumo", b =>
                {
                    b.Property<int>("IdConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsumo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Valor")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdConsumo");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("IASI_IntelligentIndustrialSolutions.Models.Equipamento", b =>
                {
                    b.Property<int>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_equipamento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamento"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_aquisicao");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo");

                    b.HasKey("IdEquipamento");

                    b.ToTable("tb_equipamento");
                });

            modelBuilder.Entity("IASI_IntelligentIndustrialSolutions.Models.Previsao", b =>
                {
                    b.Property<int>("IdPrevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_previsao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrevisao"));

                    b.Property<string>("CondicaoMeteorologica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("condicao_meteorologica");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("DirecaoVento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("direcao_vento");

                    b.Property<double>("PressaoAtmosferica")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("pressao_atmosferica");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temperatura");

                    b.Property<double>("Umidade")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("umidade");

                    b.Property<double>("VelocidadeVento")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("velocidade_vento");

                    b.HasKey("IdPrevisao");

                    b.ToTable("tb_previsao");
                });

            modelBuilder.Entity("IASI_IntelligentIndustrialSolutions.Models.Consumo", b =>
                {
                    b.HasOne("IASI_IntelligentIndustrialSolutions.Models.Equipamento", "Equipamento")
                        .WithMany("Consumos")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("IASI_IntelligentIndustrialSolutions.Models.Equipamento", b =>
                {
                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
